version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.2.16'
    volumes:
      - 'mariadb_data:/bitnami'
    environment:
      - MARIADB_USER=${DB_USER}
      - MARIADB_DATABASE=${DB_NAME}
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'stantronic/wordpress:10'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./config/wp-config.php:/bitnami/wordpress/wp-config.php
      - ./theme:/bitnami/wordpress/wp-content/themes/theme
      - wordpress_plugins:/bitnami/wordpress/wp-content/plugins
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=${DB_USER}
      - WORDPRESS_DATABASE_NAME=${DB_NAME}
      - WORDPRESS_USERNAME=${WORDPRESS_USERNAME}
      - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD}
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  mariadb_data:
    driver: local
  wordpress_plugins:
    driver: local
  theme:
  wp-config.php:
